.TH "psmq_subscribe" "3" "23 May 2021 (v0.2.1)" "bofc.pl"
.SH NAME
.PP
.BR psmq_subscribe ,\  psmq_unsubscribe
- control subscriptions for the client.
.SH SYNOPSIS
.PP
.BI "#include <psmq.h>"
.PP
.BI "int psmq_subscribe(struct psmq *" psmq ", const char *" topic ")"
.br
.BI "int psmq_unsubscribe(struct psmq *" psmq ", const char *" topic ")"
.SH DESCRIPTION
.PP
Once you connected to the broker you still won't be able to receive messages
until you subscribe to something, as broker will send only messages that are
interesting to you.
.PP
.BR psmq_subscribe (3)
allows you to tell the broker, you want to receive all messages that matches
passed
.IR topic .
You can read more about topics page
.BR psmq_overview (7)
page.
When subscribing, you can use wildcards.
.PP
.BR psmq_unsubscribe (3)
simply removes your client from given
.I topic
so you won't receive messages, that matches this
.I topic
anymore.
This must be exact
.I topic
that was used in subscribe message, including wildcard.
If you subscribed to "/can/engine/*", you have to use exacly same string
to unsubsribe, you cannot unsubscribe from "/can/engine/rpm".
If you need to receive all "/can/engine/*" messages except for
"/can/engine/rpm", you need to either subscribe to all other topics one by one,
or simply ignore "rpm" topic in you application.
.PP
.SH "EMBEDDED SYSTEM NOTES"
.PP
Both
.BR psmq_subscribe (3)
and
.BR psmq_unsubscribe (3)
will cause broker to call
.BR malloc ()
and
.BR free (),
respectively.
Belive it or not, it's to save a lots of memory.
Remember, it's not
.BR malloc ()
you should be afraid of, it's
.BR free (),
so if you only subscribe at the beginning of program (and bootup in general)
and then never unsubscribe, you don't have anything to worry about.
.SH "RETURN VALUE"
.PP
0 on success. -1 on errors with appropriate errno set.
.SH ERRORS
.TP
.B EINVAL
.I psmq
or
.I topic
is
.B NULL
.TP
.B EBADF
.I psmq
object has no yet been initialized.
.TP
.B EINVAL
.I topic
does not start from \'/\' character.
.TP
.B ENOBUFS
.I topic
is too long and doesn't fit into transmit buffer.
You need to recompile
.B psmq
with bigger
.BR PSMQ_MSG_MAX .
.SH "BUG REPORTING"
.PP
Please, report all bugs to "Michał Łyszczek <michal.lyszczek@bofc.pl>"
.SH "SEE ALSO"
.PP
.BR psmqd (1),
.BR psmq-pub (1),
.BR psmq-sub (1),
.BR psmq_cleanup (3),
.BR psmq_init (3),
.BR psmq_publish (3),
.BR psmq_receive (3),
.BR psmq_subscribe (3),
.BR psmq_timedreceive (3),
.BR psmq_timedreceive_ms (3),
.BR psmq_unsubscribe (3),
.BR psmq_building (7),
.BR psmq_overview (7).
